version: '3'

services:
  greenmail:
    image: greenmail/standalone:1.6.5
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose
      - GREENMAIL_USERS=fakemail@example.com:password
    ports:
      - 3025:3025 # SMTP
      - 3110:3110 # POP3
      - 3143:3143 # IMAP
      - 3465:3465 # SMTPS
      - 3993:3993 # IMAPS
      - 3995:3995 # POP3S
      - 8080:8080 # API

  thunderbird:
    image: jlesage/thunderbird:latest
    ports:
      - "5800:5800"  # VNC server port (for GUI access)
    environment:
      - DISPLAY=:0  # Required for GUI applications in Docker
    depends_on:
      - greenmail
    links:
      - greenmail:greenmail